@startuml button
class CButton
{
+CButton()
+~CButton()
+BOOL Create(HWND hWnd, CPixmap *pPixmap, CSound *pSound,POINT pos, int type, BOOL bMinimizeRedraw, UINT message)
+void SetIconMenu(int* pIcons, int nbIcons)
+void SetToolTips(int* pToolTips, int nbTooltips)
+void Draw()
+void Redraw()
+int GetState()
+void SetState(int state)
+int GetMenu()
+void SetMenu(int menu)
+BOOL GetEnable()
+void SetEnable(BOOL bEnable)
+BOOL GetHide()
+void SetHide(BOOL bHide)
+BOOL TreatEvent(UINT message, WPARAM wParam, LPARAM lParam)
+BOOL MouseOnButton(POINT pos)
+int GetToolTips(POINT pos)
#BOOL Detect(POINT pos)
#BOOL MouseDown(POINT pos)
#BOOL MouseMove(POINT pos)
#BOOL MouseUp(POINT pos)
#HWND m_hWnd
#CPixmap* m_pPixmap
#CDecor* m_pDecor
#CSound* m_pSound
#int m_type
#BOOL m_bEnable
#int  m_bLocked
#BOOL m_bHide
#UINT m_message
#POINT m_pos
#POINT m_dim
#int m_state
#int m_mouseState
#int m_iconMenu[20]
#int m_toolTips[20]
#int m_nbMenu
#int m_nbToolTips
#int m_selMenu
#BOOL m_bMouseDown
#BOOL m_bMinimizeRedraw
#BOOL m_bRedraw
}
class button <<functions>> {
}
@enduml