@startuml dectables
class dectables <<functions>> {
+int table_blitz[]int table_vitesse_march[]
+int table_vitesse_nage[]
+int table_vitesse_surf[]
+int table_bulldozer_left[]
+int table_bulldozer_right[]
+int table_bulldozer_turn2l[]
+int table_bulldozer_turn2r[]
+int table_poisson_left[]
+int table_poisson_right[]
+int table_poisson_turn2l[]
+int table_poisson_turn2r[]
+int table_oiseau_left[]
+int table_oiseau_right[]
+int table_oiseau_turn2l[]
+int table_oiseau_turn2r[]
+int table_guepe_left[]
+int table_guepe_right[]
+int table_guepe_turn2l[]
+int table_guepe_turn2r[]
+int table_creature_left[]
+int table_creature_right[]
+int table_creature_turn2[]
+int table_blupih_left[]
+int table_blupih_right[]
+int table_blupih_turn2l[]
+int table_blupih_turn2r[]
+int table_blupit_left[]
+int table_blupit_right[]
+int table_blupit_turn2l[]
+int table_blupit_turn2r[]
+int table_explo1[]
+int table_explo2[]
+int table_explo3[]
+int table_explo4[]
+int table_explo5[]
+int table_explo6[]
+int table_explo7[]
+int table_explo8[]
+int table_sploutch1[]
+int table_sploutch2[]
+int table_sploutch3[]
+int table_tentacule[]
+int table_bridge[]
+int table_pollution[]
+int table_invertstart[]
+int table_invertstop[]
+int table_invertpanel[]
+int table_plouf[]
+int table_tiplouf[]
+int table_blup[]
+int table_follow1[]
+int table_follow2[]
+int table_cle[]
+int table_cle1[]
+int table_cle2[]
+int table_cle3[]
+int table_decor_action[]
+int table_dynamitef[]
+int table_skate[]
+int table_glu[]
+int table_clear[]
+int table_electro[]
+int table_chenille[]
+int table_chenillei[]
+int table_adapt_decor[]
+int table_adapt_fromage[]
+int table_shield[]
+int table_shield_blupi[]
+int table_power[]
+int table_invert[]
+int table_charge[]
+int table_magicloop[]
+int table_magictrack[]
+int table_shieldloop[]
+int table_shieldtrack[]
+int table_drinkeffect[]
+int table_drinkoffset[]
+const int table_drinkoffset_size
+int table_tresortrack[]
+int table_decor_piege1[]
+int table_decor_piege2[]
+int table_decor_goutte[]
+int table_decor_ecraseur[]
+int table_decor_scie[]
+int table_decor_temp[]
+int table_decor_eau1[]
+int table_decor_eau2[]
+int table_decor_ventillod[]
+int table_decor_ventilloh[]
+int table_decor_ventillob[]
+int table_decor_ventd[]
+int table_decor_venth[]
+int table_decor_ventb[]
+int table_marine[]
+int table_36418[]
+int table_36458[]
+int table_36488[]
+int table_364a0[]
+int table_364b0[]
+int table_364d0[]
+int table_364e8[]
+int table_364f8[]
+int table_36510[]
+int table_36520[]
+int table_36530[]
+int table_36538[]
+int table_36548[]
+int table_36550[]
+int table_36570[]
+int table_365a8[]
+int table_365d0[]
+int table_365d8[]
+int table_365f0[]
+int table_36610[]
+int table_decor_lave[]
+int table_36630[]
+int table_decor_ventillog[]
+int table_decor_ventg[]
+int table_36670[]
+int table_366a0[]
+int table_366b0[]
+int table_366c0[]
+int table_366d8[]
+int table_366e8[]
+int table_366f8[]
+int table_36710[]
+int table_36748[]
+int table_mirror[]
+int table_ressort[]
+int table_blupi[]
+int table_tutorial[]
}
@enduml