@startuml misc
class misc <<functions>> {
+void InitHInstance(HINSTANCE hInstance)void OutputDebug(const char *pMessage)
+void LoadString(unsigned nID, char *pBuffer, int lgBuffer)
+void ChangeSprite(int sprite)
+POINT ConvLongToPos(LPARAM lParam)
+void InitRandom()
+int  Random(int min, int max)
+void GetCurrentDir(char *pName, int lg)
+void AddCDPath(char *pFilename)
+void AddUserPath(char *pFilename)
+void TraceErrorDD(HRESULT hErr, const char *sFile, int nLine)
+void TraceErrorDS(HRESULT hErr, const char *sFile, int nLine)
}
@enduml